### ISSUE TITLE
Hall sensor crashes system_server

### ISSUE THREAD

**Issue by TBM13** [hi6210sft-dev/issue_tracker#2]
**Build**: `lineage-17.1-20230413-UNOFFICIAL-alice`
**Device**: `CAM-L03`

**Steps:**
Any attempt to read the sensor events seem to trigger the crash. This can be done in multiple ways:
* Method one
  1. Open the [Sensor Test app](https://play.google.com/store/apps/details?id=ru.andr7e.sensortest)
  2. Press the button next to "Total:", to show all the sensors
  3. Scroll down and press the "Hall sensor akm_ak8789"
  4. Crash will occur
* Method two
   1. Open the [CPU-Z app](https://play.google.com/store/apps/details?id=com.cpuid.cpu_z&hl=es_419&gl=US)
   2. Crash will occur

**Interesting resources:**
* [Possible fix/workaround](https://github.com/skinzor/android_kernel_huawei_msm8953-1/commit/caaf21883c7b6fc636d5d74daefa46135997e9cd)

**Log highlights:**
> E/Sensors ( 2909): HallSensor,OPEN fd=273,path=/sys/class/sensors/hall_sensor/enable
> F/system_server( 2909): convert.cpp:193] Check failed: (int32_t)dst->sensorType >= (int32_t)SensorType::DEVICE_PRIVATE_BASE ((int32_t)dst->sensorType=10002, (int32_t)SensorType::DEVICE_PRIVATE_BASE=65536) 

**Full log:**
[5-hallsensor-crash.txt](https://github.com/hi6210sft-dev/issue_tracker/files/11241056/5-hallsensor-crash.txt)

**Comment by R0rt1z2** [comment]
Issue not present on ALE. [Merged](https://github.com/hi6210sft-dev/android_kernel_huawei_alice/commit/02da52e9d5c1d627b83fd1994792fcefe0b1f312) the linked resource. Waiting for further tests to confirm the bug mitigation.

**Comment by TBM13** [comment]
The issue is fixed, as the sensor is no longer exposed. I don't know whether this affects its functionality or not, I have no way of testing that.
